const words = [
  { word: "APPLE", hint: "A fruit that keeps the doctor away" },
  { word: "PYRAMID", hint: "Famous ancient structures in Egypt" },
  { word: "OCEAN", hint: "Covers most of the Earth" },
  { word: "BICYCLE", hint: "Two-wheeled vehicle" },
  { word: "COMPUTER", hint: "A machine you are coding on" },
  { word: "GUITAR", hint: "Six-string musical instrument" },
  { word: "MOUNTAIN", hint: "Very tall landform" },
  { word: "CHESS", hint: "A board game with kings and queens" },
  { word: "JUPITER", hint: "The largest planet in the Solar System" },
  { word: "PIZZA", hint: "Italian dish with cheese and toppings" },
  { word: "KANGAROO", hint: "Australian animal that jumps" },
  { word: "ROBOT", hint: "A machine that can move or act" },
  { word: "PYTHON", hint: "A programming language and a snake" },
  { word: "RAINBOW", hint: "Appears after rain and sun" },
  { word: "VAMPIRE", hint: "Mythical creature that drinks blood" },
  { word: "SOCCER", hint: "Most popular sport in the world" },
  { word: "DIAMOND", hint: "Precious stone, hardest material" },
  { word: "SPIDER", hint: "Animal with 8 legs" },
  { word: "BRIDGE", hint: "Connects two sides across water" },
  { word: "LAPTOP", hint: "Portable computer" },
  { word: "BANANA", hint: "Yellow fruit monkeys love" },
  { word: "DRAGON", hint: "Mythical fire-breathing creature" },
  { word: "VOLCANO", hint: "Mountain that erupts with lava" },
  { word: "ELEPHANT", hint: "Largest land animal" },
  { word: "TORNADO", hint: "A dangerous spinning wind storm" },
  { word: "PAINTER", hint: "An artist with a brush" },
  { word: "ZEBRA", hint: "Striped animal from Africa" },
  { word: "DOCTOR", hint: "Helps people when they are sick" },
  { word: "ISLAND", hint: "Land surrounded by water" },
  { word: "SCHOOL", hint: "Place where students learn" },
  { word: "ROCKET", hint: "Flies into space" },
  { word: "CASTLE", hint: "Big stone building for kings" },
  { word: "PRISON", hint: "Place for criminals" },
  { word: "CANDLE", hint: "Wax stick that burns with light" },
  { word: "ANGEL", hint: "Winged spiritual being" },
  { word: "MARKER", hint: "Used to highlight text" },
  { word: "TIGER", hint: "Large orange cat with stripes" },
  { word: "CLOUD", hint: "Floats in the sky" },
  { word: "GHOST", hint: "Spirit of the dead" },
  { word: "TRAIN", hint: "Runs on rails" },
  { word: "BOTTLE", hint: "Container for liquids" },
  { word: "PLANET", hint: "Orbits a star" },
  { word: "RABBIT", hint: "Animal with long ears" },
  { word: "DESERT", hint: "Dry place with little water" },
  { word: "PRINCE", hint: "Son of a king" },
  { word: "CROWN", hint: "Worn by royalty" },
  { word: "EAGLE", hint: "Large bird of prey" },
  { word: "PRISONER", hint: "Person locked in jail" },
  { word: "BREAD", hint: "Made from flour, baked" },
  { word: "KNIGHT", hint: "Medieval warrior in armor" },
  { word: "STUDENT", hint: "Learns at school" },
  { word: "RIVER", hint: "Flows to the sea" },
  { word: "CLOCK", hint: "Tells time" },
  { word: "DOLPHIN", hint: "Smart sea mammal" },
  { word: "FARMER", hint: "Works on land with crops" },
  { word: "SOLDIER", hint: "Serves in the army" },
  { word: "COOKIE", hint: "Sweet baked snack" },
  { word: "CLOWN", hint: "Performs in a circus" },
  { word: "PYRAMID", hint: "Triangle-shaped structure in Egypt" },
  { word: "MARKET", hint: "Place to buy and sell goods" },
  { word: "PENCIL", hint: "Used for writing" },
  { word: "EARTH", hint: "The planet we live on" },
  { word: "PRIEST", hint: "Religious leader" },
  { word: "HONEY", hint: "Made by bees" },
  { word: "BRAIN", hint: "Controls the body" },
  { word: "MUSIC", hint: "Art with sounds" },
  { word: "OXYGEN", hint: "Gas we breathe" },
  { word: "PRISONER", hint: "Locked in a jail" },
  { word: "HUNTER", hint: "Person who hunts animals" },
  { word: "COWBOY", hint: "Western horse rider" },
  { word: "SINGER", hint: "Performs songs" },
  { word: "PRISONER", hint: "A person held captive" },
  { word: "WIZARD", hint: "Magic user" },
  { word: "TEACHER", hint: "Educates students" },
  { word: "FISHING", hint: "Catching fish" },
  { word: "SUNSET", hint: "When the sun goes down" },
  { word: "PRISONER", hint: "Detained by law" },
  { word: "CANDLE", hint: "Wax stick with a flame" },
  { word: "SHADOW", hint: "Dark shape made by blocking light" },
  { word: "MIRROR", hint: "Reflects images" },
  { word: "WINTER", hint: "The coldest season" },
  { word: "SUMMER", hint: "The hottest season" },
  { word: "SPRING", hint: "Season when flowers bloom" },
  { word: "AUTUMN", hint: "Season of falling leaves" },
  { word: "METAL", hint: "Material like iron or gold" },
  { word: "RULER", hint: "Used to measure length" },
  { word: "CANDLE", hint: "Burns to give light" },
  { word: "SNAKE", hint: "Legless reptile" },
  { word: "FROG", hint: "Amphibian that jumps" },
  { word: "GIRAFFE", hint: "Tall animal with long neck" },
  { word: "MONKEY", hint: "Climbs trees, loves bananas" },
  { word: "BEAR", hint: "Big animal that hibernates" },
  { word: "PANDA", hint: "Black and white bear" },
  { word: "FOX", hint: "Small clever animal" },
  { word: "OWL", hint: "Bird that hoots at night" },
  { word: "HORSE", hint: "Animal people ride" },
  { word: "WHALE", hint: "Largest sea mammal" }
];